name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: "Build node"
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Build
        run: npm run full-build
  lint:
    runs-on: ubuntu-latest

    name: "Lint on ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Lint & check formatting
        run: npm run rome-ci
      # - name: test on Rust
      #   run: wasm-pack test --node
