name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE_**"
      - ".pre-commit-config.yaml"
  repository_dispatch:
    types: [release-notification]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: macos-latest
    permissions: # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - name: Setup
        run: |
          rustup update stable
          # cargo install wasm-pack
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Update
        run: |
          cargo update
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic update \`Cargo.lock\`"
      - name: Build
        run: |
          npm run full-build || (cargo clean | npm run full-build)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
